Django/Django 4/lesson_08/mysite/myauth/urls.py
from django.urls import path
from .views import get_cookie_view, set_cookie_view, set_session_view, get_session_view, MylogoutView, AboutMeView, RegisterView, FooBarView, HelloView
from django.contrib.auth.views import LoginView

app_name = "myauth"

urlpatterns = [
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",  # имя шаблона, если нет то будет искать registration/login.html
            redirect_authenticated_user=True,  # редирект для уже залогиненых пользоваетлей, в settings, без этого ищет account/profile
        ),
        name="login"),
    # path("logout/", logout_view, name="logout"),
    path("hello/", HelloView.as_view(), name="hello"),
    path("logout/", MylogoutView.as_view(), name="logout"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("register/", RegisterView.as_view(), name="register"),
    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),
    path("session/get", get_session_view, name="session-get"),
    path("session/set", set_session_view, name="session-set"),
    path("foo-bar/", FooBarView.as_view(), name="foo-bar")
]

Django/Django 4/lesson_08/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from .sitemaps import sitemaps

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name="schema"),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/', include('myapiapp.urls')),
    path('blog/', include('blogapp.urls')),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap"
    )


]

urlpatterns += i18n_patterns(
    path('myauth/', include('myauth.urls')),
    path('shop/', include('shopapp.urls'))
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls"))
    )

Django/Django 4/lesson_08/mysite/shopapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from django.views.decorators.cache import cache_page
from .views import (ShopIndexView,
                    GroupsListView,
                    ProductDetailView,
                    ProductsListView,
                    OrderListView,
                    OrderDetailView,
                    ProductCreateView,
                    ProductUpdateView,
                    ProductDeleteView,
                    ProductsDataExportView,
                    ProductViewSet)


app_name = 'shopapp'

routers = DefaultRouter()
routers.register("products", ProductViewSet)

urlpatterns = [
    # path('', cache_page(60 * 3)(ShopIndexView.as_view()), name='index'),
    path('', ShopIndexView.as_view(), name='index'),
    path('api/', include(routers.urls)),
    path('groups/', GroupsListView.as_view(), name='groups_list'),
    path('products/', ProductsListView.as_view(), name='products_list'),
    path('products/export/', ProductsDataExportView.as_view(), name='products-export'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product_details'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('orders/', OrderListView.as_view(), name='orders_list'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order_details',)

]

Django/Django 4/lesson_08/mysite/shopapp/forms.py
from django import forms
from django.core import validators

from .models import Product
from django.contrib.auth.models import Group


# class ProductForm(forms.Form):
#     name = forms.CharField(max_length=100)
#     price = forms.DecimalField(min_value=1, max_value=100000, decimal_places=2)
#     description = forms.CharField(
#         label="Product description",
#         widget=forms.Textarea(attrs={"rows": 5, "cols": '30'}),
#         validators=[validators.RegexValidator(  # добавили валидатор регулярных выражений
#             regex=r"great",
#             message="Field must contain word 'great'"
#         )]
#     )

# class ProductForm(forms.ModelForm):
#     class Meta:
#         model = Product
#         fields = "name", "price", "description", "discount"


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = "name",


class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True


class MultipleFileField(forms.ImageField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "name", "price", "description", "discount", "preview"

    images = MultipleFileField()


class CSVImportForm(forms.Form):
    """
    Создаем новую форму для загрузки csv файла
    """
    csv_file = forms.FileField()

Django/Django 4/lesson_08/mysite/shopapp/views.py
"""
В этом модуле лежат различные наборы представлений.

Разные view интернет-магазина: по товарам, заказам и т.д.
"""

import logging
from csv import DictWriter
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, JsonResponse
from django.contrib.auth.models import Group
from timeit import default_timer
from .models import Product, Order, ProductImage
from .forms import GroupForm, ProductForm
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from rest_framework.viewsets import ModelViewSet
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.decorators import action  # позволяет поключить любую вью функцию к вью сету
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.parsers import MultiPartParser
from django_filters.rest_framework import DjangoFilterBackend
from .serializers import ProductSerializer
from drf_spectacular.utils import extend_schema, OpenApiResponse
from .common import save_csv_products
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.core.cache import cache

log = logging.getLogger(__name__)


@extend_schema(description="Product views CRUD")
class ProductViewSet(ModelViewSet):
    """
    Набор представлений для действий над Product
    Полный CRUD для сущностей товара
    """
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [SearchFilter, DjangoFilterBackend, OrderingFilter]
    search_fields = [
        "name", "description"
    ]
    filterset_fields = [
        'name',
        'description',
        'price',
        'discount',
        'archived',
    ]

    ordering_fields = [
        'name',
        'price',
        'discount',
    ]

    @extend_schema(
        summary="Get one product by ID",
        description="Retrives product, return 404 if not found",
        responses={
            200: ProductSerializer,
            404: OpenApiResponse(description="Empty response, product by id not found"),
        }
    )
    def retrieve(self, *args, **kwargs):
        return super().retrieve(*args, **kwargs)

    @method_decorator(cache_page(60 * 2))
    def list(self, *args, **kwargs):  #  переопределяем метод для получения списка
        print("hello products list")
        return super().list(*args, **kwargs)

    @action(methods=["get"],
            detail=False)  # False укажет что путь к download_csv на основе адресов для списка элементов
    def download_csv(self, request: Request):
        """
        Для скачки products в формате csv
        """
        response = HttpResponse(content_type="text/csv")
        filename = "products=export.csv"
        response["Content-Disposition"] = f"attachment; filename={filename}-export.csv"
        queryset = self.filter_queryset(self.get_queryset())
        fields = [
            "name",
            'description',
            'price',
            'discount',
        ]
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()

        for product in queryset:
            writer.writerow({
                field: getattr(product, field)
                for field in fields
            })
        return response


    @action(
        detail=False,
        methods=["post"],
        parser_classes=[MultiPartParser]
    )
    def upload_csv(self, request: Request):
        products = save_csv_products(
            request.FILES["file"].file,
            encoding=request.encoding
        )
        serializer = self.get_serializer(products, many=True)
        return Response(serializer.data)



class ShopIndexView(View):
    # @method_decorator(cache_page(60 * 2)) можно так или в urls.py
    def get(self, request: HttpRequest) -> HttpResponse:
        products = [
            ('Laptop', 999),
            ('Desktop', 1999),
            ('Iphone', 2999),
        ]
        context = {
            'time_running': default_timer(),
            'products': products,
            "items": 5,
        }
        log.debug("Products for shop index: %s", products)
        log.info("Rendering shop index")
        return render(request, 'shopapp/shop-index.html', context=context)


# def shop_index(request: HttpRequest):
#     products = [
#         ('Laptop', 999),
#         ('Desktop', 1999),
#         ('Iphone', 2999),
#     ]
#     context = {
#         'time_running': default_timer(),
#         'products': products
#     }
#     return render(request, 'shopapp/shop-index.html', context=context)


class GroupsListView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            "form": GroupForm,
            'groups': Group.objects.prefetch_related('permissions').all()
        }
        return render(request, 'shopapp/groups-list.html', context=context)

    def post(self, request: HttpRequest):
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
        # return self.get(request) так можно но нежелательно
        return redirect(request.path)  # возвращаем путь на эту же страницу


# def groups_list(request: HttpRequest):
#     context = {
#         'groups': Group.objects.prefetch_related('permissions').all(),
#     }
#     return render(request, 'shopapp/groups-list.html', context=context)


class ProductDetailView(DetailView):
    template_name = 'shopapp/products-detail.html'
    # model = Product
    queryset = Product.objects.filter(archived=False).prefetch_related(
        "images")  # чтобы архивные продукты не отображались
    context_object_name = "product"


# class ProductDetailView(View):
#     def get(self, request: HttpRequest, pk: int) -> HttpResponse:
#         # product = Product.objects.get(pk=pk)  # так можно, но при вводе несуществующего продукта будет ошибка сервера
#         product = get_object_or_404(Product, pk=pk)  # или вывод продукта из БД или ошибка 404
#         context = {
#             "product": product
#         }
#         return render(request, "shopapp/products-detail.html", context=context)


class ProductsListView(ListView):
    template_name = 'shopapp/products_list.html'
    # model = Product
    queryset = Product.objects.filter(archived=False)  # чтобы архивные продукты не отображались
    context_object_name = "products_list"  # указываем по какой переменной будут передаваться модель в шаблон


# class ProductsListView(TemplateView):
#     template_name = 'shopapp/products_list.html'
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['products_list'] = Product.objects.all()
#         return context


# def products_list(request: HttpRequest):
#     context = {
#         'products_list': Product.objects.all()
#     }
#     return render(request, 'shopapp/products_list.html', context=context)


class ProductCreateView(UserPassesTestMixin, CreateView):
    def test_func(self):
        # return self.request.user.groups.filter(name="secret-group").exists()  #  существует ли такое условие
        return self.request.user.is_superuser  # если пользователь СУПЕР то доступ разрешен

    model = Product
    form_class = ProductForm
    # fields = "name", "price", "description", "discount", "preview"  # или указываем поля, или указываем форму ниже
    success_url = reverse_lazy("shopapp:products_list")  # ссылки можно генерировать только в View функции поэтому так

    def form_valid(self, form):
        response = super().form_valid(form)
        images = form.cleaned_data["images"]
        for image in images:
            ProductImage.objects.create(
                product=self.object,
                image=image
            )

        return response


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    # fields = "name", "price", "description", "discount", "preview"
    template_name_suffix = "_update_form"

    def get_success_url(self):  # генерируем ссылку для возврата к деталям товара
        return reverse(
            "shopapp:product_details",  # ссылка куда переадресовываем
            kwargs={"pk": self.object.pk}  # ссылка на pk обьекта который мы обновили
        )

    def form_valid(self, form):
        response = super().form_valid(form)
        images = form.cleaned_data["images"]
        for image in images:
            ProductImage.objects.create(
                product=self.object,
                image=image
            )

        return response


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("shopapp:products_list")

    def form_valid(self, form):  # функция выполняется если форма валидна
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


# def product_create(request: HttpRequest) -> HttpResponse:
#     if request.method == "POST":  # проверяем какой метод
#         form = ProductForm(request.POST)  # получаем заполненную форму
#         if form.is_valid():  # проверяем валидность формы
#             # name = form.cleaned_data['name'] Clean_data это словарь
#             # price = form.cleaned_data['price']
#             # Product.objects.create(name, price) Можно и так передавать, но это долго
#             # Product.objects.create(**form.cleaned_data)  # распаковываем словарь и передаем в базу данных всю форму
#             form.save()
#             url = reverse('shopapp:products_list')  # генерируем ссылку для перехода
#             return redirect(url)  # открываем ссылку

Django/Django 4/lesson_08/mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Базовый блок
        {% endblock %}
    </title>
</head>
<body>
    {% block body %}
        Базовый блок
    {% endblock  %}
    <div>
        {% now 'l' as current_weekday %}
        Today is {{current_weekday}}
    </div>
</body>
</html>

Django/Django 4/lesson_08/mysite/shopapp/templates/shopapp/create-product.html
{% extends "shopapp/base.html" %}

{% block title %}
    Create new product
{% endblock %}

{% block body %}
    <h1>Create new product!</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Create</button>
        </form>
    </div>

    <div>
        <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
    </div>
{% endblock %}

Django/Django 4/lesson_08/mysite/shopapp/templates/shopapp/groups-list.html
{% extends "shopapp/base.html" %}

{% block title %}
    Groups List
{% endblock  %}

{% block body %}
    <h1> Groups: </h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    {% if not groups %}
        <div> Групп нет </div>
    {% else %}
        <ul>
            {% for group in groups %}
                <li> 
                    <div> {{group.name}} </div>
                    <ul>
                        {% for permission in group.permissions.all %}
                            <li> {{permission}} </li>
                        {% endfor %}
                    </ul>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock  %}

Django/Django 4/lesson_08/mysite/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Order #{{ object.pk }} details
{% endblock %}

{% block body %}
    <h1>Order #{{ object.pk }}</h1>
    <div>
        <p>Order by {% firstof object.user.first_name order.user.username %}</p>
        <p>Promocode <code>{{ object.promocode }}</code> </p>
        <p>Delivery address {{ object.delivery_address }}</p>
        <div>
            Products in order
            <ul>
                {% for product in object.products.all %}
                    <li>{{ product.name }} for $ {{product.price }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
<div><a href="{% url 'shopapp:orders_list' %}">Back to order list</a></div>
{% endblock %}

Django/Django 4/lesson_08/mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Orders list
{% endblock %}

{% block body %}
    <h1>Orders:</h1>
    <div>
        {% if object_list %}
            <div>
                {% for order in object_list %}
                    <div>
                        <p><a href="{% url 'shopapp:order_details' pk=order.pk %}">Details</a></p>
                        <p>Order by {% firstof order.user.first_name order.user.username %}</p>
                        <p>Promocode <code>{{ order.promocode }}</code> </p>
                        <p>Delivery address {{ order.delivery_address }}</p>
                        <div>
                            Products in order
                            <ul>
                                {% for product in order.products.all %}
                                    <li>{{ product.name }} for $ {{product.price }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <h3>No orders yet</h3>
        {% endif %}
    </div>
{% endblock %}

Django/Django 4/lesson_08/mysite/shopapp/templates/shopapp/orders-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Orders list
{% endblock %}

{% block body %}
    <h1>Orders:</h1>
    <div>
        {% if orders %}
            <div>
                {% for order in orders %}
                    <div>
                        <p>Order by {% firstof order.user.first_name order.user.username %}</p>
                        <p>Promocode <code>{{ order.promocode }}</code> </p>
                        <p>Delivery address {{ order.delivery_address }}</p>
                        <div>
                            Products in order
                            <ul>
                                {% for product in order.products.all %}
                                    <li>{{ product.name }} for $ {{product.price }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <h3>No orders yet</h3>
        {% endif %}
    </div>
{% endblock %}

Django/Django 4/lesson_08/mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Confirm delete {{ object.name }}
{% endblock %}

{% block body %}
    <h1>Are you sure you want to delete {{ object.name }}</h1>
<br>
    <div>
        <a href="{% url 'shopapp:product_details' pk=object.pk %}">
            Back to product
        </a>
    </div>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Delete</button>
        </form>
    </div>
<br>
{% endblock %}

Django/Django 4/lesson_08/mysite/shopapp/templates/shopapp/product_form.html
{% extends "shopapp/base.html" %}

{% block title %}
    Create new product
{% endblock %}

{% block body %}
    <h1>Create new product!</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Create</button>
        </form>
    </div>

    <div>
        <a href="{% url 'shopapp:products_list' %}">Back to products list</a>
    </div>
{% endblock %}

Django/Django 4/lesson_08/mysite/shopapp/templates/shopapp/product_update_form.html
{% extends "shopapp/base.html" %}

{% block title %}
    Update new product
{% endblock %}

{% block body %}
    <h1>Update new product!</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Update</button>
        </form>
    </div>

    <div>
        <a href="{% url 'shopapp:product_details' pk=object.pk %}">Back to product #{{ object.pk }}</a>
    </div>
{% endblock %}

Django/Django 4/lesson_08/mysite/shopapp/templates/shopapp/products-detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Product #{{ product.pk }}
{% endblock %}

{% block body %}
    <h1>Product <strong>{{ product.name }}</strong></h1>
    <div>
        <div>Description: <em>{{ product.description }}</em></div>
        <div>Price: {{ product.price }}</div>
        <div>Discount: {{ product.discount }}</div>
        <div>Archived: {{ product.archived }}</div>
        {% if product.preview %}
          <img src="{{product.preview.url}}" alt="{{product.preview.name}}">
        {% endif %}
        <h3>Images:</h3>
        <div>
            {% for img in product.images.all %}
                <div>
                    <img src="{{ img.image.url}}" alt="{{ img.image.name }}">
                    <div>{{ img.description }}</div>
                </div>
            {% empty %}
                <div>No images upload yet</div>
            {% endfor %}
        </div>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}">Back to product list</a>
    </div>
    <div>
        <a href="{% url 'shopapp:product_update' pk=product.pk %}">Update product</a>
    </div>
    <div>
        <a href="{% url 'shopapp:product_delete' pk=product.pk %}">Delete product</a>
    </div>
{% endblock %}

Django/Django 4/lesson_08/mysite/shopapp/templates/shopapp/products_changelist.html
{% extends 'admin/change_list.html' %}
<!-- эта страница которая выводит список продуктов в админке. Это мы делаем чтобы добавить кнопку-->
{% block object-tools-items %}
    <li>
        <a href="{% url 'admin:import_products_csv' %}" class="addlink">
            Import CSV
        </a>
    </li>
    {{ block.super }} <!-- продолжаем этот блок родительским контентом -->
{% endblock %}

Django/Django 4/lesson_08/mysite/shopapp/templates/shopapp/products_list.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
  {% translate 'Products list' %}
{% endblock %}

{% block body %}
  <h1>{% translate 'Products' %}:</h1>
  {% if products_list %}
    <div>
    {% blocktranslate count products_count=products_list|length %}
      There is only one product.
      {% plural %}
      There are {{ products_count }} products.
    {% endblocktranslate %}
    </div>
    <div>
      {% for product in products_list %}
      <div>
        <p><a href="{% url 'shopapp:product_details' pk=product.pk %}">{% translate 'Name' context 'product name' %}: {{product.name}}</a></p>
        <p>{% translate 'Price' %}: {{product.price}}</p>
        {% translate 'no discount' as no_discount %}
        <p>{% translate 'Discount' %}: {% firstof product.discount no_discount %}</p>
        {% if product.preview %}
          <img src="{{product.preview.url}}" alt="{{product.preview.name}}">
        {% endif %}
      </div>
      {% endfor %}
    </div>
  <div>
    <a href="{% url 'shopapp:product_create' %}">
      {% translate 'Create new product' %}
    </a>
  </div>
  {% else %}
    {% url 'shopapp:product_create' as create_product_url %}
    {% blocktranslate %}
    <div>No products</div>
    <a href="{{ create_product_url }}">
      Create a new one
    </a>
    {% endblocktranslate %}
  {% endif %}
  

{% endblock %}

Django/Django 4/lesson_08/mysite/shopapp/templates/shopapp/shop-index.html
{% extends "shopapp/base.html" %}
{% load cache %}

{% block title %}
    Свой заголовок
{% endblock  %}

{% block body %}
    <ul>
        {% for name, price in products %}
            <li> {{name}} ({{name|length}}) for $ {{price}} </li>
        {% empty %}
            <span> Список пуст </span>
        {% endfor %}
    </ul>
    <div>
        <strong>
            You have {{ items }} cherr{{ items|pluralize:"y,ies" }}
        </strong>
    </div>
    {% cache 100 lorem %}
    {% lorem 3 p random %}
    {% endcache %}
{% endblock %}